name: Java CI with Gradle
on: [release, create, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Jar
      uses: actions/upload-artifact@v1
      with:
        name: jar
        path: build/libs
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: jar
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/libs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
